// /home/valerie-brown/Documents/Temporum/temporum-online/src/tests/testSuite.js

import { allTests } from './testDefinitions.js';

// This file selects which tests to run from the master list in testDefinitions.js.
// To add or remove tests from a run, simply add or remove their `testId`
// from the `activeTestIds` array below.

const activeTestIds = [
  "StoneAge_1",
  "AncientEgypt_1",
  "AncientEgypt_scoreNoCards",
  "IceAge_1",
  "TimeOfLegends_1",
  "IronAge_1",

  "RomanEmpire_1",
  "RomanEmpire_2",
  "PaxBuddha_1",
  "PaxBuddha_2",
  "PaxBuddha_3",
  "Renaissance_2",
  "FeudalJapan_2",
  "FeudalJapan_3",
  "ImperialChina_1",
  "ImperialChina_2",
  "ImperialChina_3",
  "ImperialChina_4",
  "AgeOfCults_1",
  "AgeOfCults_2",
  "Crusades_2",
  "Crusades_3",
  "Plague_1",
  "Plague_2",
  "Plague_3",
  "Plague_4",
  "HolyNorseEmpire_2",
  "Inquisition_2",
  "Inquisition_3",
  "Inquisition_4",
  "AztecInvasion_2",
  "EgyptianAmerica_2",

  "AgeOfDiscovery_1",
  "BalloonRevolution_1",
  "AmericanCivilWar_1",
  "Plutocracy_1",
  "Plutocracy_2",
  "ProhibitionEra_1",
  "ProhibitionEra_2",
  "Bureaucracy_1",
  "Bureaucracy_2",
  "Bureaucracy_3",
  "FrenchRevolution_1",
  "IndustrialRevolution_1",
  "IndustrialRevolution_2",
  "IndustrialRevolution_3",
  "IndustrialRevolution_4",

  "NanotechWonderland_1",
  "NanotechWonderland_2",
  "RobotUprising_1",
  "RobotUprising_2",
  "SpaceAge_1",
  "SpaceAge_2",
  "SpaceAge_3",
  "SpaceAge_4",
  "Utopia_1",
  "AgeOfCats_1",
  "AgeOfCats_2",
  "AgeOfCats_3",
  "AgeOfToys_1",
  "AgeOfToys_2",
  "AgeOfToys_3",
  "AgeOfToys_4",
  "CommunistUtopia_1",
  "CommunistUtopia_2",
  "CommunistUtopia_3",
  "CommunistUtopia_4",
  "NuclearWasteland_1",
  "Savagery_1",
  "Savagery_2",
  "Savagery_3",
  "SteampunkEmpire_1",
  "SteampunkEmpire_2",
  "IcyWasteland_1",
  "IcyWasteland_2",
  "IcyWasteland_3",
  "IcyWasteland_4",
  "WarmGlobe_1",
  "WarmGlobe_2",
  "WarmGlobe_3",
  "WarmGlobe_4",
  "WarmGlobe_5",
  "InformationAge_1",
  "InformationAge_2",
  "InformationAge_3",
  "InformationAge_4",

  "TrojanWar_1",
  "DawnOfMan_1",
  "AgeOfAtlantis_HQ_1",
  "AgeOfAtlantis_HQ_2",
  "BabylonianBazaar_1",
  "BabylonianBazaar_2",
  "BabylonianBazaar_3",

  "Amazons_1",
  "MongolianEmpire_1",
  "MongolianEmpire_2",
  "MongolianEmpire_3",
  "GreekAmerica_1",
  "GreekAmerica_2",
  "ScientistEnclave_1",
  "ScientistEnclave_2",
  "ScientistEnclave_3",
  "AncientCarthage_1",
  "ByzantineEmpire_1",
  "ByzantineEmpire_2",
  "VikingAmerica_1",
  "VikingAmerica_2",
  "VikingAmerica_3",
  "CelticParadise_1",
  "CelticParadise_2",

  "DutchGoldenAge_1",
  "DutchGoldenAge_2",
  "PaxBritannica_1",
  "PaxBritannica_2",
  "PaxBritannica_3",
  "AtomicAge_1",
  "AgeOfPlastic_1",
  "AgeOfPlastic_2",
  "AgeOfPlastic_3",
  "AgeOfPlastic_4",
  "AgeOfPlastic_5",
  "AgeOfPlastic_6",
  "AgeOfPlastic_7",
  "AgeOfPiracy_1",
  "AgeOfPiracy_2",
  "AgeOfPiracy_3",
  "Y2K_1",
  "Y2K_2",

  "AgeOfSuperheroes_1",
  "AgeOfSuperheroes_2",
  "AgeOfSuperheroes_3",
  "AgeOfSuperheroes_4",
  "FloatingCities_1",
  "FloatingCities_2",
  "SimulatedParadise_1",
  "SimulatedParadise_2",
  "SimulatedParadise_IceAge_1",
  "SimulatedParadise_RomanEmpire_1",
  "SimulatedParadise_DutchGoldenAge_1",
  "SimulatedParadise_HQ",
  "Singularity_1",
  "Singularity_2",
];

// Filter the full list of tests to get only the active ones.
const activeTestSuite = allTests.filter(test => activeTestIds.includes(test.testId));

export default activeTestSuite;
