// This file is a "barrel" file for all services.
// It re-exports functions and variables from other service modules,
// providing a single, convenient entry point for the rest of the application.

export { gameData, user, localPlayerHand } from "./state.js";
export {
  createLobby,
  listenToLobby,
  joinLobby,
  exitLobby,
  stopListeningToLobby,
  startGame,
  addAIPlayer,
  removePlayer, 
  removeSpectator,
  updateSelectedZone,
  updateInitialCard,
  updateTimeline,
  toggleTestMode,
  selectPlayerColor,
  resignGame,
  replacePlayerWithAI,
  runAITest,
  leaveTestLobby,
  becomeSpectator,
  updateAlternateRealities,
} from "./lobbyService.js";
export {
  changeHistory,
  declineChangeHistory,
  visitZone,
  scoreCard,
  playCard,
  advanceCrown,
  executeChoice,
  resolveOptionalZone,
  discardAndContinue,
  resolveDiscardForMoney,
  resolveInquisition,
  discardMany, 
  resolveInventor,
  resolveBabylonianChoice,
  resolveGizmoChoice,
  retreatCrown,
  resolvePredictTheFuture,
  selectCyberneticsPerpetual,
  selectCyberneticsHandCard,
  resolveInvestments,
  resolveTreasureMap,
  resolveTradeGoods,
  resolveToysChoice,
  selectCardToPass,
  returnCard,
  resolveSimulatedParadiseChoice,
  resolveMove,
  resolveSetHQ,
  resolveY2KDiscard,
} from "./prompt.js";
export { runAIAction, clearAIPromptMemory } from "./aiService.js";